// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: DeskBandServerManager.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace DeskBandServer.Grpc {

  /// <summary>Holder for reflection information generated from DeskBandServerManager.proto</summary>
  public static partial class DeskBandServerManagerReflection {

    #region Descriptor
    /// <summary>File descriptor for DeskBandServerManager.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static DeskBandServerManagerReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChtEZXNrQmFuZFNlcnZlck1hbmFnZXIucHJvdG8SE0Rlc2tCYW5kU2VydmVy",
            "LkdycGMaGlNlcnZlckluZnJhc3RydWN0dXJlLnByb3RvImEKFkNvbmZpZ01z",
            "Z1NlcnZlclJlcXVlc3QSEgoKU2VydmVyUG9ydBgBIAEoBRIbChNPbmx5QWNj",
            "ZXB0TG9jYWxob3N0GAIgASgIEhYKDkRlZmF1bHRDb250ZW50GAMgASgJIhYK",
            "FENvbmZpZ01zZ1NlcnZlclJlcGx5IhEKD0dldFN0eWxlUmVxdWVzdCLzAQoN",
            "R2V0U3R5bGVSZXBseRI0CgpCYWNrZ3JvdW5kGAEgASgLMiAuRGVza0JhbmRT",
            "ZXJ2ZXIuR3JwYy5DdXN0b21Db2xvchI1CgtCb3JkZXJDb2xvchgCIAEoCzIg",
            "LkRlc2tCYW5kU2VydmVyLkdycGMuQ3VzdG9tQ29sb3ISFwoPQm9yZGVyVGhp",
            "Y2tuZXNzGAMgASgNEhQKDENvcm5lclJhZGl1cxgEIAEoDRIQCghGb250U2l6",
            "ZRgFIAEoDRI0CgpGb3JlZ3JvdW5kGAYgASgLMiAuRGVza0JhbmRTZXJ2ZXIu",
            "R3JwYy5DdXN0b21Db2xvciL1AQoPU2V0U3R5bGVSZXF1ZXN0EjQKCkJhY2tn",
            "cm91bmQYASABKAsyIC5EZXNrQmFuZFNlcnZlci5HcnBjLkN1c3RvbUNvbG9y",
            "EjUKC0JvcmRlckNvbG9yGAIgASgLMiAuRGVza0JhbmRTZXJ2ZXIuR3JwYy5D",
            "dXN0b21Db2xvchIXCg9Cb3JkZXJUaGlja25lc3MYAyABKA0SFAoMQ29ybmVy",
            "UmFkaXVzGAQgASgNEhAKCEZvbnRTaXplGAUgASgNEjQKCkZvcmVncm91bmQY",
            "BiABKAsyIC5EZXNrQmFuZFNlcnZlci5HcnBjLkN1c3RvbUNvbG9yIjIKDVNl",
            "dFN0eWxlUmVwbHkSDwoHc3VjY2VzcxgBIAEoCBIQCghFcnJvck1zZxgCIAEo",
            "CSIcChpTdGFydEdycGNNc2dTZXJ2aWNlUmVxdWVzdCIvChhTdGFydEdycGNN",
            "c2dTZXJ2aWNlUmVwbHkSEwoLR3JwY01zZ1BvcnQYASABKAUiGwoZU3RvcEdy",
            "cGNNc2dTZXJ2aWNlUmVxdWVzdCIuChdTdG9wR3JwY01zZ1NlcnZpY2VSZXBs",
            "eRITCgtHcnBjTXNnUG9ydBgBIAEoBTKaBAoWRGVza0JhbmRTZXJ2aWNlTWFu",
            "YWdlchJUCghHZXRTdHlsZRIkLkRlc2tCYW5kU2VydmVyLkdycGMuR2V0U3R5",
            "bGVSZXF1ZXN0GiIuRGVza0JhbmRTZXJ2ZXIuR3JwYy5HZXRTdHlsZVJlcGx5",
            "EmkKD0NvbmZpZ01zZ1NlcnZlchIrLkRlc2tCYW5kU2VydmVyLkdycGMuQ29u",
            "ZmlnTXNnU2VydmVyUmVxdWVzdBopLkRlc2tCYW5kU2VydmVyLkdycGMuQ29u",
            "ZmlnTXNnU2VydmVyUmVwbHkSVAoIU2V0U3R5bGUSJC5EZXNrQmFuZFNlcnZl",
            "ci5HcnBjLlNldFN0eWxlUmVxdWVzdBoiLkRlc2tCYW5kU2VydmVyLkdycGMu",
            "U2V0U3R5bGVSZXBseRJ1ChNTdGFydEdycGNNc2dTZXJ2aWNlEi8uRGVza0Jh",
            "bmRTZXJ2ZXIuR3JwYy5TdGFydEdycGNNc2dTZXJ2aWNlUmVxdWVzdBotLkRl",
            "c2tCYW5kU2VydmVyLkdycGMuU3RhcnRHcnBjTXNnU2VydmljZVJlcGx5EnIK",
            "ElN0b3BHcnBjTXNnU2VydmljZRIuLkRlc2tCYW5kU2VydmVyLkdycGMuU3Rv",
            "cEdycGNNc2dTZXJ2aWNlUmVxdWVzdBosLkRlc2tCYW5kU2VydmVyLkdycGMu",
            "U3RvcEdycGNNc2dTZXJ2aWNlUmVwbHliBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::DeskBandServer.Grpc.ServerInfrastructureReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::DeskBandServer.Grpc.ConfigMsgServerRequest), global::DeskBandServer.Grpc.ConfigMsgServerRequest.Parser, new[]{ "ServerPort", "OnlyAcceptLocalhost", "DefaultContent" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DeskBandServer.Grpc.ConfigMsgServerReply), global::DeskBandServer.Grpc.ConfigMsgServerReply.Parser, null, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DeskBandServer.Grpc.GetStyleRequest), global::DeskBandServer.Grpc.GetStyleRequest.Parser, null, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DeskBandServer.Grpc.GetStyleReply), global::DeskBandServer.Grpc.GetStyleReply.Parser, new[]{ "Background", "BorderColor", "BorderThickness", "CornerRadius", "FontSize", "Foreground" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DeskBandServer.Grpc.SetStyleRequest), global::DeskBandServer.Grpc.SetStyleRequest.Parser, new[]{ "Background", "BorderColor", "BorderThickness", "CornerRadius", "FontSize", "Foreground" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DeskBandServer.Grpc.SetStyleReply), global::DeskBandServer.Grpc.SetStyleReply.Parser, new[]{ "Success", "ErrorMsg" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DeskBandServer.Grpc.StartGrpcMsgServiceRequest), global::DeskBandServer.Grpc.StartGrpcMsgServiceRequest.Parser, null, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DeskBandServer.Grpc.StartGrpcMsgServiceReply), global::DeskBandServer.Grpc.StartGrpcMsgServiceReply.Parser, new[]{ "GrpcMsgPort" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DeskBandServer.Grpc.StopGrpcMsgServiceRequest), global::DeskBandServer.Grpc.StopGrpcMsgServiceRequest.Parser, null, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DeskBandServer.Grpc.StopGrpcMsgServiceReply), global::DeskBandServer.Grpc.StopGrpcMsgServiceReply.Parser, new[]{ "GrpcMsgPort" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ConfigMsgServerRequest : pb::IMessage<ConfigMsgServerRequest> {
    private static readonly pb::MessageParser<ConfigMsgServerRequest> _parser = new pb::MessageParser<ConfigMsgServerRequest>(() => new ConfigMsgServerRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ConfigMsgServerRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DeskBandServer.Grpc.DeskBandServerManagerReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigMsgServerRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigMsgServerRequest(ConfigMsgServerRequest other) : this() {
      serverPort_ = other.serverPort_;
      onlyAcceptLocalhost_ = other.onlyAcceptLocalhost_;
      defaultContent_ = other.defaultContent_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigMsgServerRequest Clone() {
      return new ConfigMsgServerRequest(this);
    }

    /// <summary>Field number for the "ServerPort" field.</summary>
    public const int ServerPortFieldNumber = 1;
    private int serverPort_;
    /// <summary>
    /// Grpc 服务端口
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ServerPort {
      get { return serverPort_; }
      set {
        serverPort_ = value;
      }
    }

    /// <summary>Field number for the "OnlyAcceptLocalhost" field.</summary>
    public const int OnlyAcceptLocalhostFieldNumber = 2;
    private bool onlyAcceptLocalhost_;
    /// <summary>
    /// 只接受本机的消息
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool OnlyAcceptLocalhost {
      get { return onlyAcceptLocalhost_; }
      set {
        onlyAcceptLocalhost_ = value;
      }
    }

    /// <summary>Field number for the "DefaultContent" field.</summary>
    public const int DefaultContentFieldNumber = 3;
    private string defaultContent_ = "";
    /// <summary>
    /// 启动时默认显示的内容
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string DefaultContent {
      get { return defaultContent_; }
      set {
        defaultContent_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ConfigMsgServerRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ConfigMsgServerRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ServerPort != other.ServerPort) return false;
      if (OnlyAcceptLocalhost != other.OnlyAcceptLocalhost) return false;
      if (DefaultContent != other.DefaultContent) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ServerPort != 0) hash ^= ServerPort.GetHashCode();
      if (OnlyAcceptLocalhost != false) hash ^= OnlyAcceptLocalhost.GetHashCode();
      if (DefaultContent.Length != 0) hash ^= DefaultContent.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ServerPort != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ServerPort);
      }
      if (OnlyAcceptLocalhost != false) {
        output.WriteRawTag(16);
        output.WriteBool(OnlyAcceptLocalhost);
      }
      if (DefaultContent.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(DefaultContent);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ServerPort != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ServerPort);
      }
      if (OnlyAcceptLocalhost != false) {
        size += 1 + 1;
      }
      if (DefaultContent.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DefaultContent);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ConfigMsgServerRequest other) {
      if (other == null) {
        return;
      }
      if (other.ServerPort != 0) {
        ServerPort = other.ServerPort;
      }
      if (other.OnlyAcceptLocalhost != false) {
        OnlyAcceptLocalhost = other.OnlyAcceptLocalhost;
      }
      if (other.DefaultContent.Length != 0) {
        DefaultContent = other.DefaultContent;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ServerPort = input.ReadInt32();
            break;
          }
          case 16: {
            OnlyAcceptLocalhost = input.ReadBool();
            break;
          }
          case 26: {
            DefaultContent = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class ConfigMsgServerReply : pb::IMessage<ConfigMsgServerReply> {
    private static readonly pb::MessageParser<ConfigMsgServerReply> _parser = new pb::MessageParser<ConfigMsgServerReply>(() => new ConfigMsgServerReply());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ConfigMsgServerReply> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DeskBandServer.Grpc.DeskBandServerManagerReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigMsgServerReply() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigMsgServerReply(ConfigMsgServerReply other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigMsgServerReply Clone() {
      return new ConfigMsgServerReply(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ConfigMsgServerReply);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ConfigMsgServerReply other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ConfigMsgServerReply other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    }

  }

  public sealed partial class GetStyleRequest : pb::IMessage<GetStyleRequest> {
    private static readonly pb::MessageParser<GetStyleRequest> _parser = new pb::MessageParser<GetStyleRequest>(() => new GetStyleRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetStyleRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DeskBandServer.Grpc.DeskBandServerManagerReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetStyleRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetStyleRequest(GetStyleRequest other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetStyleRequest Clone() {
      return new GetStyleRequest(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetStyleRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetStyleRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetStyleRequest other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    }

  }

  public sealed partial class GetStyleReply : pb::IMessage<GetStyleReply> {
    private static readonly pb::MessageParser<GetStyleReply> _parser = new pb::MessageParser<GetStyleReply>(() => new GetStyleReply());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetStyleReply> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DeskBandServer.Grpc.DeskBandServerManagerReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetStyleReply() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetStyleReply(GetStyleReply other) : this() {
      background_ = other.background_ != null ? other.background_.Clone() : null;
      borderColor_ = other.borderColor_ != null ? other.borderColor_.Clone() : null;
      borderThickness_ = other.borderThickness_;
      cornerRadius_ = other.cornerRadius_;
      fontSize_ = other.fontSize_;
      foreground_ = other.foreground_ != null ? other.foreground_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetStyleReply Clone() {
      return new GetStyleReply(this);
    }

    /// <summary>Field number for the "Background" field.</summary>
    public const int BackgroundFieldNumber = 1;
    private global::DeskBandServer.Grpc.CustomColor background_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::DeskBandServer.Grpc.CustomColor Background {
      get { return background_; }
      set {
        background_ = value;
      }
    }

    /// <summary>Field number for the "BorderColor" field.</summary>
    public const int BorderColorFieldNumber = 2;
    private global::DeskBandServer.Grpc.CustomColor borderColor_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::DeskBandServer.Grpc.CustomColor BorderColor {
      get { return borderColor_; }
      set {
        borderColor_ = value;
      }
    }

    /// <summary>Field number for the "BorderThickness" field.</summary>
    public const int BorderThicknessFieldNumber = 3;
    private uint borderThickness_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint BorderThickness {
      get { return borderThickness_; }
      set {
        borderThickness_ = value;
      }
    }

    /// <summary>Field number for the "CornerRadius" field.</summary>
    public const int CornerRadiusFieldNumber = 4;
    private uint cornerRadius_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint CornerRadius {
      get { return cornerRadius_; }
      set {
        cornerRadius_ = value;
      }
    }

    /// <summary>Field number for the "FontSize" field.</summary>
    public const int FontSizeFieldNumber = 5;
    private uint fontSize_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint FontSize {
      get { return fontSize_; }
      set {
        fontSize_ = value;
      }
    }

    /// <summary>Field number for the "Foreground" field.</summary>
    public const int ForegroundFieldNumber = 6;
    private global::DeskBandServer.Grpc.CustomColor foreground_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::DeskBandServer.Grpc.CustomColor Foreground {
      get { return foreground_; }
      set {
        foreground_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetStyleReply);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetStyleReply other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Background, other.Background)) return false;
      if (!object.Equals(BorderColor, other.BorderColor)) return false;
      if (BorderThickness != other.BorderThickness) return false;
      if (CornerRadius != other.CornerRadius) return false;
      if (FontSize != other.FontSize) return false;
      if (!object.Equals(Foreground, other.Foreground)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (background_ != null) hash ^= Background.GetHashCode();
      if (borderColor_ != null) hash ^= BorderColor.GetHashCode();
      if (BorderThickness != 0) hash ^= BorderThickness.GetHashCode();
      if (CornerRadius != 0) hash ^= CornerRadius.GetHashCode();
      if (FontSize != 0) hash ^= FontSize.GetHashCode();
      if (foreground_ != null) hash ^= Foreground.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (background_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Background);
      }
      if (borderColor_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(BorderColor);
      }
      if (BorderThickness != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(BorderThickness);
      }
      if (CornerRadius != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(CornerRadius);
      }
      if (FontSize != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(FontSize);
      }
      if (foreground_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Foreground);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (background_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Background);
      }
      if (borderColor_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(BorderColor);
      }
      if (BorderThickness != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(BorderThickness);
      }
      if (CornerRadius != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(CornerRadius);
      }
      if (FontSize != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(FontSize);
      }
      if (foreground_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Foreground);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetStyleReply other) {
      if (other == null) {
        return;
      }
      if (other.background_ != null) {
        if (background_ == null) {
          Background = new global::DeskBandServer.Grpc.CustomColor();
        }
        Background.MergeFrom(other.Background);
      }
      if (other.borderColor_ != null) {
        if (borderColor_ == null) {
          BorderColor = new global::DeskBandServer.Grpc.CustomColor();
        }
        BorderColor.MergeFrom(other.BorderColor);
      }
      if (other.BorderThickness != 0) {
        BorderThickness = other.BorderThickness;
      }
      if (other.CornerRadius != 0) {
        CornerRadius = other.CornerRadius;
      }
      if (other.FontSize != 0) {
        FontSize = other.FontSize;
      }
      if (other.foreground_ != null) {
        if (foreground_ == null) {
          Foreground = new global::DeskBandServer.Grpc.CustomColor();
        }
        Foreground.MergeFrom(other.Foreground);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (background_ == null) {
              Background = new global::DeskBandServer.Grpc.CustomColor();
            }
            input.ReadMessage(Background);
            break;
          }
          case 18: {
            if (borderColor_ == null) {
              BorderColor = new global::DeskBandServer.Grpc.CustomColor();
            }
            input.ReadMessage(BorderColor);
            break;
          }
          case 24: {
            BorderThickness = input.ReadUInt32();
            break;
          }
          case 32: {
            CornerRadius = input.ReadUInt32();
            break;
          }
          case 40: {
            FontSize = input.ReadUInt32();
            break;
          }
          case 50: {
            if (foreground_ == null) {
              Foreground = new global::DeskBandServer.Grpc.CustomColor();
            }
            input.ReadMessage(Foreground);
            break;
          }
        }
      }
    }

  }

  public sealed partial class SetStyleRequest : pb::IMessage<SetStyleRequest> {
    private static readonly pb::MessageParser<SetStyleRequest> _parser = new pb::MessageParser<SetStyleRequest>(() => new SetStyleRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SetStyleRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DeskBandServer.Grpc.DeskBandServerManagerReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SetStyleRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SetStyleRequest(SetStyleRequest other) : this() {
      background_ = other.background_ != null ? other.background_.Clone() : null;
      borderColor_ = other.borderColor_ != null ? other.borderColor_.Clone() : null;
      borderThickness_ = other.borderThickness_;
      cornerRadius_ = other.cornerRadius_;
      fontSize_ = other.fontSize_;
      foreground_ = other.foreground_ != null ? other.foreground_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SetStyleRequest Clone() {
      return new SetStyleRequest(this);
    }

    /// <summary>Field number for the "Background" field.</summary>
    public const int BackgroundFieldNumber = 1;
    private global::DeskBandServer.Grpc.CustomColor background_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::DeskBandServer.Grpc.CustomColor Background {
      get { return background_; }
      set {
        background_ = value;
      }
    }

    /// <summary>Field number for the "BorderColor" field.</summary>
    public const int BorderColorFieldNumber = 2;
    private global::DeskBandServer.Grpc.CustomColor borderColor_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::DeskBandServer.Grpc.CustomColor BorderColor {
      get { return borderColor_; }
      set {
        borderColor_ = value;
      }
    }

    /// <summary>Field number for the "BorderThickness" field.</summary>
    public const int BorderThicknessFieldNumber = 3;
    private uint borderThickness_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint BorderThickness {
      get { return borderThickness_; }
      set {
        borderThickness_ = value;
      }
    }

    /// <summary>Field number for the "CornerRadius" field.</summary>
    public const int CornerRadiusFieldNumber = 4;
    private uint cornerRadius_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint CornerRadius {
      get { return cornerRadius_; }
      set {
        cornerRadius_ = value;
      }
    }

    /// <summary>Field number for the "FontSize" field.</summary>
    public const int FontSizeFieldNumber = 5;
    private uint fontSize_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint FontSize {
      get { return fontSize_; }
      set {
        fontSize_ = value;
      }
    }

    /// <summary>Field number for the "Foreground" field.</summary>
    public const int ForegroundFieldNumber = 6;
    private global::DeskBandServer.Grpc.CustomColor foreground_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::DeskBandServer.Grpc.CustomColor Foreground {
      get { return foreground_; }
      set {
        foreground_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SetStyleRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SetStyleRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Background, other.Background)) return false;
      if (!object.Equals(BorderColor, other.BorderColor)) return false;
      if (BorderThickness != other.BorderThickness) return false;
      if (CornerRadius != other.CornerRadius) return false;
      if (FontSize != other.FontSize) return false;
      if (!object.Equals(Foreground, other.Foreground)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (background_ != null) hash ^= Background.GetHashCode();
      if (borderColor_ != null) hash ^= BorderColor.GetHashCode();
      if (BorderThickness != 0) hash ^= BorderThickness.GetHashCode();
      if (CornerRadius != 0) hash ^= CornerRadius.GetHashCode();
      if (FontSize != 0) hash ^= FontSize.GetHashCode();
      if (foreground_ != null) hash ^= Foreground.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (background_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Background);
      }
      if (borderColor_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(BorderColor);
      }
      if (BorderThickness != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(BorderThickness);
      }
      if (CornerRadius != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(CornerRadius);
      }
      if (FontSize != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(FontSize);
      }
      if (foreground_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Foreground);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (background_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Background);
      }
      if (borderColor_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(BorderColor);
      }
      if (BorderThickness != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(BorderThickness);
      }
      if (CornerRadius != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(CornerRadius);
      }
      if (FontSize != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(FontSize);
      }
      if (foreground_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Foreground);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SetStyleRequest other) {
      if (other == null) {
        return;
      }
      if (other.background_ != null) {
        if (background_ == null) {
          Background = new global::DeskBandServer.Grpc.CustomColor();
        }
        Background.MergeFrom(other.Background);
      }
      if (other.borderColor_ != null) {
        if (borderColor_ == null) {
          BorderColor = new global::DeskBandServer.Grpc.CustomColor();
        }
        BorderColor.MergeFrom(other.BorderColor);
      }
      if (other.BorderThickness != 0) {
        BorderThickness = other.BorderThickness;
      }
      if (other.CornerRadius != 0) {
        CornerRadius = other.CornerRadius;
      }
      if (other.FontSize != 0) {
        FontSize = other.FontSize;
      }
      if (other.foreground_ != null) {
        if (foreground_ == null) {
          Foreground = new global::DeskBandServer.Grpc.CustomColor();
        }
        Foreground.MergeFrom(other.Foreground);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (background_ == null) {
              Background = new global::DeskBandServer.Grpc.CustomColor();
            }
            input.ReadMessage(Background);
            break;
          }
          case 18: {
            if (borderColor_ == null) {
              BorderColor = new global::DeskBandServer.Grpc.CustomColor();
            }
            input.ReadMessage(BorderColor);
            break;
          }
          case 24: {
            BorderThickness = input.ReadUInt32();
            break;
          }
          case 32: {
            CornerRadius = input.ReadUInt32();
            break;
          }
          case 40: {
            FontSize = input.ReadUInt32();
            break;
          }
          case 50: {
            if (foreground_ == null) {
              Foreground = new global::DeskBandServer.Grpc.CustomColor();
            }
            input.ReadMessage(Foreground);
            break;
          }
        }
      }
    }

  }

  public sealed partial class SetStyleReply : pb::IMessage<SetStyleReply> {
    private static readonly pb::MessageParser<SetStyleReply> _parser = new pb::MessageParser<SetStyleReply>(() => new SetStyleReply());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SetStyleReply> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DeskBandServer.Grpc.DeskBandServerManagerReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SetStyleReply() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SetStyleReply(SetStyleReply other) : this() {
      success_ = other.success_;
      errorMsg_ = other.errorMsg_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SetStyleReply Clone() {
      return new SetStyleReply(this);
    }

    /// <summary>Field number for the "success" field.</summary>
    public const int SuccessFieldNumber = 1;
    private bool success_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Success {
      get { return success_; }
      set {
        success_ = value;
      }
    }

    /// <summary>Field number for the "ErrorMsg" field.</summary>
    public const int ErrorMsgFieldNumber = 2;
    private string errorMsg_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ErrorMsg {
      get { return errorMsg_; }
      set {
        errorMsg_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SetStyleReply);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SetStyleReply other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Success != other.Success) return false;
      if (ErrorMsg != other.ErrorMsg) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Success != false) hash ^= Success.GetHashCode();
      if (ErrorMsg.Length != 0) hash ^= ErrorMsg.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Success != false) {
        output.WriteRawTag(8);
        output.WriteBool(Success);
      }
      if (ErrorMsg.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ErrorMsg);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Success != false) {
        size += 1 + 1;
      }
      if (ErrorMsg.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ErrorMsg);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SetStyleReply other) {
      if (other == null) {
        return;
      }
      if (other.Success != false) {
        Success = other.Success;
      }
      if (other.ErrorMsg.Length != 0) {
        ErrorMsg = other.ErrorMsg;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Success = input.ReadBool();
            break;
          }
          case 18: {
            ErrorMsg = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class StartGrpcMsgServiceRequest : pb::IMessage<StartGrpcMsgServiceRequest> {
    private static readonly pb::MessageParser<StartGrpcMsgServiceRequest> _parser = new pb::MessageParser<StartGrpcMsgServiceRequest>(() => new StartGrpcMsgServiceRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<StartGrpcMsgServiceRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DeskBandServer.Grpc.DeskBandServerManagerReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StartGrpcMsgServiceRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StartGrpcMsgServiceRequest(StartGrpcMsgServiceRequest other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StartGrpcMsgServiceRequest Clone() {
      return new StartGrpcMsgServiceRequest(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as StartGrpcMsgServiceRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(StartGrpcMsgServiceRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(StartGrpcMsgServiceRequest other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    }

  }

  public sealed partial class StartGrpcMsgServiceReply : pb::IMessage<StartGrpcMsgServiceReply> {
    private static readonly pb::MessageParser<StartGrpcMsgServiceReply> _parser = new pb::MessageParser<StartGrpcMsgServiceReply>(() => new StartGrpcMsgServiceReply());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<StartGrpcMsgServiceReply> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DeskBandServer.Grpc.DeskBandServerManagerReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StartGrpcMsgServiceReply() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StartGrpcMsgServiceReply(StartGrpcMsgServiceReply other) : this() {
      grpcMsgPort_ = other.grpcMsgPort_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StartGrpcMsgServiceReply Clone() {
      return new StartGrpcMsgServiceReply(this);
    }

    /// <summary>Field number for the "GrpcMsgPort" field.</summary>
    public const int GrpcMsgPortFieldNumber = 1;
    private int grpcMsgPort_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int GrpcMsgPort {
      get { return grpcMsgPort_; }
      set {
        grpcMsgPort_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as StartGrpcMsgServiceReply);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(StartGrpcMsgServiceReply other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (GrpcMsgPort != other.GrpcMsgPort) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (GrpcMsgPort != 0) hash ^= GrpcMsgPort.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (GrpcMsgPort != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(GrpcMsgPort);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (GrpcMsgPort != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(GrpcMsgPort);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(StartGrpcMsgServiceReply other) {
      if (other == null) {
        return;
      }
      if (other.GrpcMsgPort != 0) {
        GrpcMsgPort = other.GrpcMsgPort;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            GrpcMsgPort = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class StopGrpcMsgServiceRequest : pb::IMessage<StopGrpcMsgServiceRequest> {
    private static readonly pb::MessageParser<StopGrpcMsgServiceRequest> _parser = new pb::MessageParser<StopGrpcMsgServiceRequest>(() => new StopGrpcMsgServiceRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<StopGrpcMsgServiceRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DeskBandServer.Grpc.DeskBandServerManagerReflection.Descriptor.MessageTypes[8]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StopGrpcMsgServiceRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StopGrpcMsgServiceRequest(StopGrpcMsgServiceRequest other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StopGrpcMsgServiceRequest Clone() {
      return new StopGrpcMsgServiceRequest(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as StopGrpcMsgServiceRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(StopGrpcMsgServiceRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(StopGrpcMsgServiceRequest other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    }

  }

  public sealed partial class StopGrpcMsgServiceReply : pb::IMessage<StopGrpcMsgServiceReply> {
    private static readonly pb::MessageParser<StopGrpcMsgServiceReply> _parser = new pb::MessageParser<StopGrpcMsgServiceReply>(() => new StopGrpcMsgServiceReply());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<StopGrpcMsgServiceReply> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DeskBandServer.Grpc.DeskBandServerManagerReflection.Descriptor.MessageTypes[9]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StopGrpcMsgServiceReply() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StopGrpcMsgServiceReply(StopGrpcMsgServiceReply other) : this() {
      grpcMsgPort_ = other.grpcMsgPort_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StopGrpcMsgServiceReply Clone() {
      return new StopGrpcMsgServiceReply(this);
    }

    /// <summary>Field number for the "GrpcMsgPort" field.</summary>
    public const int GrpcMsgPortFieldNumber = 1;
    private int grpcMsgPort_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int GrpcMsgPort {
      get { return grpcMsgPort_; }
      set {
        grpcMsgPort_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as StopGrpcMsgServiceReply);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(StopGrpcMsgServiceReply other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (GrpcMsgPort != other.GrpcMsgPort) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (GrpcMsgPort != 0) hash ^= GrpcMsgPort.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (GrpcMsgPort != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(GrpcMsgPort);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (GrpcMsgPort != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(GrpcMsgPort);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(StopGrpcMsgServiceReply other) {
      if (other == null) {
        return;
      }
      if (other.GrpcMsgPort != 0) {
        GrpcMsgPort = other.GrpcMsgPort;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            GrpcMsgPort = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
