# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import DeskBandServer_pb2 as DeskBandServer__pb2


class DeskBandServiceStub(object):
    """DeskBand服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSize = channel.unary_unary(
                '/DeskBandServer.Grpc.DeskBandService/GetSize',
                request_serializer=DeskBandServer__pb2.GetSizeRequest.SerializeToString,
                response_deserializer=DeskBandServer__pb2.GetSizeReply.FromString,
                )
        self.ShowTextMessage = channel.unary_unary(
                '/DeskBandServer.Grpc.DeskBandService/ShowTextMessage',
                request_serializer=DeskBandServer__pb2.ShowTextMessageRequest.SerializeToString,
                response_deserializer=DeskBandServer__pb2.ShowTextMessageReply.FromString,
                )


class DeskBandServiceServicer(object):
    """DeskBand服务
    """

    def GetSize(self, request, context):
        """获取DeskBand区域大小
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShowTextMessage(self, request, context):
        """在DeskBand区域内显示文本内容
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DeskBandServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSize': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSize,
                    request_deserializer=DeskBandServer__pb2.GetSizeRequest.FromString,
                    response_serializer=DeskBandServer__pb2.GetSizeReply.SerializeToString,
            ),
            'ShowTextMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.ShowTextMessage,
                    request_deserializer=DeskBandServer__pb2.ShowTextMessageRequest.FromString,
                    response_serializer=DeskBandServer__pb2.ShowTextMessageReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DeskBandServer.Grpc.DeskBandService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DeskBandService(object):
    """DeskBand服务
    """

    @staticmethod
    def GetSize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DeskBandServer.Grpc.DeskBandService/GetSize',
            DeskBandServer__pb2.GetSizeRequest.SerializeToString,
            DeskBandServer__pb2.GetSizeReply.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ShowTextMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DeskBandServer.Grpc.DeskBandService/ShowTextMessage',
            DeskBandServer__pb2.ShowTextMessageRequest.SerializeToString,
            DeskBandServer__pb2.ShowTextMessageReply.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
