# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DeskBandServer.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DeskBandServer.proto',
  package='DeskBandServer.Grpc',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x14\x44\x65skBandServer.proto\x12\x13\x44\x65skBandServer.Grpc\"\x10\n\x0eGetSizeRequest\"-\n\x0cGetSizeReply\x12\r\n\x05Width\x18\x01 \x01(\x05\x12\x0e\n\x06Height\x18\x02 \x01(\x05\"9\n\x0b\x43ustomColor\x12\t\n\x01\x41\x18\x01 \x01(\r\x12\t\n\x01R\x18\x02 \x01(\r\x12\t\n\x01G\x18\x03 \x01(\r\x12\t\n\x01\x42\x18\x04 \x01(\r\"n\n\x16ShowTextMessageRequest\x12\r\n\x05MsgID\x18\x01 \x01(\t\x12\x0f\n\x07\x43ontent\x18\x02 \x01(\t\x12\x34\n\nForeground\x18\x03 \x01(\x0b\x32 .DeskBandServer.Grpc.CustomColor\"%\n\x14ShowTextMessageReply\x12\r\n\x05MsgID\x18\x01 \x01(\t2\xcf\x01\n\x0f\x44\x65skBandService\x12Q\n\x07GetSize\x12#.DeskBandServer.Grpc.GetSizeRequest\x1a!.DeskBandServer.Grpc.GetSizeReply\x12i\n\x0fShowTextMessage\x12+.DeskBandServer.Grpc.ShowTextMessageRequest\x1a).DeskBandServer.Grpc.ShowTextMessageReplyb\x06proto3'
)




_GETSIZEREQUEST = _descriptor.Descriptor(
  name='GetSizeRequest',
  full_name='DeskBandServer.Grpc.GetSizeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=61,
)


_GETSIZEREPLY = _descriptor.Descriptor(
  name='GetSizeReply',
  full_name='DeskBandServer.Grpc.GetSizeReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Width', full_name='DeskBandServer.Grpc.GetSizeReply.Width', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Height', full_name='DeskBandServer.Grpc.GetSizeReply.Height', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=108,
)


_CUSTOMCOLOR = _descriptor.Descriptor(
  name='CustomColor',
  full_name='DeskBandServer.Grpc.CustomColor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='A', full_name='DeskBandServer.Grpc.CustomColor.A', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='R', full_name='DeskBandServer.Grpc.CustomColor.R', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='G', full_name='DeskBandServer.Grpc.CustomColor.G', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='B', full_name='DeskBandServer.Grpc.CustomColor.B', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=167,
)


_SHOWTEXTMESSAGEREQUEST = _descriptor.Descriptor(
  name='ShowTextMessageRequest',
  full_name='DeskBandServer.Grpc.ShowTextMessageRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='MsgID', full_name='DeskBandServer.Grpc.ShowTextMessageRequest.MsgID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Content', full_name='DeskBandServer.Grpc.ShowTextMessageRequest.Content', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Foreground', full_name='DeskBandServer.Grpc.ShowTextMessageRequest.Foreground', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=169,
  serialized_end=279,
)


_SHOWTEXTMESSAGEREPLY = _descriptor.Descriptor(
  name='ShowTextMessageReply',
  full_name='DeskBandServer.Grpc.ShowTextMessageReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='MsgID', full_name='DeskBandServer.Grpc.ShowTextMessageReply.MsgID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=281,
  serialized_end=318,
)

_SHOWTEXTMESSAGEREQUEST.fields_by_name['Foreground'].message_type = _CUSTOMCOLOR
DESCRIPTOR.message_types_by_name['GetSizeRequest'] = _GETSIZEREQUEST
DESCRIPTOR.message_types_by_name['GetSizeReply'] = _GETSIZEREPLY
DESCRIPTOR.message_types_by_name['CustomColor'] = _CUSTOMCOLOR
DESCRIPTOR.message_types_by_name['ShowTextMessageRequest'] = _SHOWTEXTMESSAGEREQUEST
DESCRIPTOR.message_types_by_name['ShowTextMessageReply'] = _SHOWTEXTMESSAGEREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetSizeRequest = _reflection.GeneratedProtocolMessageType('GetSizeRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETSIZEREQUEST,
  '__module__' : 'DeskBandServer_pb2'
  # @@protoc_insertion_point(class_scope:DeskBandServer.Grpc.GetSizeRequest)
  })
_sym_db.RegisterMessage(GetSizeRequest)

GetSizeReply = _reflection.GeneratedProtocolMessageType('GetSizeReply', (_message.Message,), {
  'DESCRIPTOR' : _GETSIZEREPLY,
  '__module__' : 'DeskBandServer_pb2'
  # @@protoc_insertion_point(class_scope:DeskBandServer.Grpc.GetSizeReply)
  })
_sym_db.RegisterMessage(GetSizeReply)

CustomColor = _reflection.GeneratedProtocolMessageType('CustomColor', (_message.Message,), {
  'DESCRIPTOR' : _CUSTOMCOLOR,
  '__module__' : 'DeskBandServer_pb2'
  # @@protoc_insertion_point(class_scope:DeskBandServer.Grpc.CustomColor)
  })
_sym_db.RegisterMessage(CustomColor)

ShowTextMessageRequest = _reflection.GeneratedProtocolMessageType('ShowTextMessageRequest', (_message.Message,), {
  'DESCRIPTOR' : _SHOWTEXTMESSAGEREQUEST,
  '__module__' : 'DeskBandServer_pb2'
  # @@protoc_insertion_point(class_scope:DeskBandServer.Grpc.ShowTextMessageRequest)
  })
_sym_db.RegisterMessage(ShowTextMessageRequest)

ShowTextMessageReply = _reflection.GeneratedProtocolMessageType('ShowTextMessageReply', (_message.Message,), {
  'DESCRIPTOR' : _SHOWTEXTMESSAGEREPLY,
  '__module__' : 'DeskBandServer_pb2'
  # @@protoc_insertion_point(class_scope:DeskBandServer.Grpc.ShowTextMessageReply)
  })
_sym_db.RegisterMessage(ShowTextMessageReply)



_DESKBANDSERVICE = _descriptor.ServiceDescriptor(
  name='DeskBandService',
  full_name='DeskBandServer.Grpc.DeskBandService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=321,
  serialized_end=528,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetSize',
    full_name='DeskBandServer.Grpc.DeskBandService.GetSize',
    index=0,
    containing_service=None,
    input_type=_GETSIZEREQUEST,
    output_type=_GETSIZEREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ShowTextMessage',
    full_name='DeskBandServer.Grpc.DeskBandService.ShowTextMessage',
    index=1,
    containing_service=None,
    input_type=_SHOWTEXTMESSAGEREQUEST,
    output_type=_SHOWTEXTMESSAGEREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DESKBANDSERVICE)

DESCRIPTOR.services_by_name['DeskBandService'] = _DESKBANDSERVICE

# @@protoc_insertion_point(module_scope)
